homebrew_taps: []
homebrew_cask_packages:
  - 1password
  - WebStorm
  - biscuit
  - brave-browser
  - browserosaurus
  - cleanmymac
  - codex-app
  # - docker
  - firefox
  - fork
  - gemini
  - google-chrome
  - google-chrome@beta
  - google-chrome@canary
  - google-chrome@dev
  - google-cloud-sdk
  # - google-japanese-ime
  - raycast
  - visual-studio-code
  - warp
  # - yoink
homebrew_packages:
  - ansible
  - bat
  - docker
  - fnm
  - fzf
  - git
  - jq
  - mas
  - terraform
  - tldr
  - wget
app_store_packages:
  - id: 937984704
    name: Amphetamine
  - id: 540348655
    name: MonoSnap
