- block:

  - name: homebrew cask packages install
    homebrew_cask: name={{ item }} state=installed
    environment:
      HOMEBREW_CASK_OPTS: "--appdir=/Applications"
    with_items: '{{ homebrew_cask_packages }}'

  tags:
    - homebrew_cask
